Ordinamento:	 ordinamento.o Main.o
	gcc  ordinamento.o Main.o -o Ordinamento

ordinamento.o: ordinamento.c
	gcc -c ordinamento.c
Main.o:	Main.c
	gcc -c Main.c
clean:
	rm -rf ordinamento.o Main.o Ordinamento