Libreria: item.o BST.o stack.o libreria.o main.o
	gcc item.o BST.o stack.o libreria.o main.o -o Libreria

item.o:	item.c
	gcc -c item.c

BST.o:	BST.c
	gcc -c BST.c

stack.o:stack.c
	gcc -c stack.c

libreria.o: libreria.c
	gcc -c libreria.c

main.o:	main.c
	gcc -c main.c

clean:
	rm -rf item.o BST.o stack.o libreria.o main.o Libreria